### ISSUE TITLE
JavaScript clase 1

### ISSUE THREAD

**Issue by Ailinchu** [CodeStrong2023/Error_404Scrum#3]
Clase 1 - Néstor

**Comment by NeGoSi** [comment]
el código ya esta terminado, en estos momentos estoy por empezar a subirlo a la rama de github

**Comment by NeGoSi** [comment]
el commit se ha ejecutado con éxito, espero respuestas sobre la revisión del código!

**Comment by Ailinchu** [comment]
Recibido, todo ok.
